"""
Groq AI-powered Recommendation Service.
Generates personalized, context-aware retention recommendations using Groq LLM.
"""

import os
import json
import logging
from typing import Dict, Any, Optional

try:
    import groq
except ImportError:
    groq = None

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GROQ_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You are an expert HR Analytics and Employee Retention Consultant.

Your job is to analyze employee retention predictions generated by a machine learning model and provide practical recommendations for HR managers.

You will receive:
1. Employee information
2. ML prediction probabilities
3. Employee risk category

Your task is to:
- Explain why the employee may stay or leave.
- Identify key risk factors.
- Identify positive retention factors.
- Recommend actions HR should take.
- Prioritize recommendations by impact.
- Estimate retention improvement potential.

Do NOT simply repeat the prediction percentage.

Base your recommendations on the employee attributes and prediction results.

Risk Categories:
- Low Risk: Employee has high probability of staying. Focus on engagement and career growth.
- Medium Risk: Employee shows early warning signs. Recommend proactive interventions.
- High Risk: Employee has significant likelihood of leaving. Recommend urgent retention measures.

Consider factors such as:
- Monthly Income
- Overtime
- Years At Company
- Years In Current Role
- Promotion History
- Training Opportunities
- Distance From Home
- Department
- Job Role
- Performance Rating
- Environment Satisfaction
- Relationship Satisfaction

Identify which features contribute most to employee retention risk.

Recommendation Logic:
- If Overtime is high: Recommend workload balancing.
- If Income is below department average: Recommend compensation review.
- If Promotion gap > 3 years: Recommend career progression discussion.
- If Years At Company are high and promotions are low: Recommend leadership opportunities.
- If Training Participation is low: Recommend skill development programs.

Return ONLY valid JSON, no markdown fences, no extra text.

Output format:
{
  "employee_summary": "",
  "risk_assessment": "",
  "key_risk_factors": [""],
  "positive_factors": [""],
  "recommended_actions": [
    {
      "priority": "High|Medium|Low",
      "action": "",
      "reason": ""
    }
  ],
  "retention_score": 0,
  "estimated_retention_improvement": "",
  "final_recommendation": ""
}
"""


class GroqRecommendationService:
    """AI-powered recommendation service using Groq LLM."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or GROQ_API_KEY
        self.client = None
        self._available = False
        self._init_client()

    def _init_client(self):
        """Initialise the Groq client."""
        if not self.api_key:
            logger.warning("No GROQ_API_KEY set — AI recommendations disabled")
            return
        try:
            self.client = groq.Groq(api_key=self.api_key)
            self._available = True
            logger.info("Groq AI recommendation service initialised")
        except Exception as e:
            logger.warning(f"Could not initialise Groq client: {e}")

    @property
    def is_available(self) -> bool:
        return self._available and self.client is not None

    def generate_recommendations(
        self,
        employee_data: Dict[str, Any],
        prediction_result: Dict[str, Any],
        shap_contributions: Dict[str, Any] = None,
    ) -> Optional[Dict[str, Any]]:
        """Generate AI-powered recommendations via Groq."""
        if not self.is_available:
            return None

        try:
            user_msg = self._build_prompt(employee_data, prediction_result, shap_contributions)

            response = self.client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
                temperature=0.5,
                top_p=0.85,
                max_tokens=1500,
                response_format={"type": "json_object"},
            )

            raw = response.choices[0].message.content.strip()
            parsed = json.loads(raw)

            # Handle the new structured output format
            # Map recommended_actions to our recommendations structure
            rec_actions = parsed.get("recommended_actions", [])
            recs = []
            for ra in rec_actions[:5]:
                recs.append({
                    "title": ra.get("action", "Retention Action"),
                    "description": ra.get("reason", ""),
                    "priority": ra.get("priority", "medium").lower(),
                    "category": "retention",
                })

            # Also try the old format for backward compatibility during transition
            if not recs:
                recs = parsed.get("recommendations", [])

            summary = parsed.get("employee_summary", parsed.get("summary", ""))

            result = {
                "recommendations": recs,
                "summary": summary,
                # Include richer fields for the frontend
                "risk_assessment": parsed.get("risk_assessment", ""),
                "key_risk_factors": parsed.get("key_risk_factors", []),
                "positive_factors": parsed.get("positive_factors", []),
                "retention_score": parsed.get("retention_score", None),
                "estimated_retention_improvement": parsed.get("estimated_retention_improvement", ""),
                "final_recommendation": parsed.get("final_recommendation", ""),
            }

            if not recs:
                return None

            logger.info(f"Groq generated {len(recs)} recommendations")
            return result

        except json.JSONDecodeError as e:
            logger.warning(f"Groq response was not valid JSON: {e}")
            return None
        except Exception as e:
            logger.warning(f"Groq recommendation error: {e}")
            return None

    def _build_prompt(
        self,
        employee_data: Dict[str, Any],
        prediction_result: Dict[str, Any],
        shap_contributions: Dict[str, Any] = None,
    ) -> str:
        """Build a rich, detailed prompt for the LLM."""
        parts = []

        # Employee information
        parts.append("## Employee Information")
        key_fields = [
            ("age", "Age"), ("gender", "Gender"), ("department", "Department"),
            ("job_role", "Job Role"), ("monthly_income", "Monthly Income"),
            ("education", "Education Level"), ("overtime", "Overtime"),
            ("years_at_company", "Years At Company"),
            ("years_since_last_promotion", "Years Since Last Promotion"),
            ("job_satisfaction", "Job Satisfaction (1-5)"),
            ("work_life_balance", "Work-Life Balance (1-5)"),
            ("performance_rating", "Performance Rating"),
            ("salary_level", "Salary Level"),
            ("num_projects", "Number of Projects"),
            ("avg_monthly_hours", "Average Monthly Hours"),
            ("satisfaction_level", "Satisfaction Score (0-1)"),
            ("last_evaluation", "Last Evaluation Score (0-1)"),
            ("time_spend_company", "Tenure (years)"),
            ("training_times_last_year", "Training Sessions Last Year"),
            ("distance_from_home", "Distance From Home (km)"),
            ("marital_status", "Marital Status"),
        ]
        for field, label in key_fields:
            val = employee_data.get(field)
            if val is not None:
                parts.append(f"- {label}: {val}")

        # ML Prediction
        parts.append("\n## ML Prediction")
        prob = prediction_result.get("attrition_probability", "N/A")
        risk = prediction_result.get("risk_level", "N/A")
        confidence = prediction_result.get("confidence", "N/A")
        parts.append(f"- Attrition Probability: {prob}%")
        parts.append(f"- Risk Level: {risk}")
        parts.append(f"- Prediction: {prediction_result.get('prediction', 'N/A')}")

        # SHAP contributions — root cause analysis
        if shap_contributions:
            contribs = shap_contributions.get("feature_contributions", {})
            if contribs:
                parts.append("\n## Key Risk Factors (SHAP Analysis)")
                for i, (feature, value) in enumerate(list(contribs.items())[:8], 1):
                    parts.append(f"  {i}. {feature}: {value}")

        parts.append("\n---")
        parts.append("Analyze this employee's retention risk and provide professional HR recommendations.")

        return "\n".join(parts)
